# Generated by Django 3.0.11 on 2020-12-29 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20201130_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone is invalid', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')])),
                ('otp', models.CharField(max_length=10)),
                ('key', models.BinaryField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='is_username_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone is invalid', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')]),
        ),
    ]
