# Generated by Django 3.0.11 on 2021-03-19 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20210310_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone is invalid', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')]),
        ),
    ]
