# Generated by Django 3.0.11 on 2021-03-22 06:01

from django.db import migrations, models


def migrate_empty_to_null(apps, schema_editor):

    UserModel = apps.get_model('user_management', 'User')

    for user in UserModel.objects.all():
        user.email = None if user.tmp_email == '' else user.tmp_email
        user.first_name = None if user.tmp_first_name == '' else user.tmp_first_name
        user.last_name = None if user.last_name == '' else user.tmp_last_name
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20210319_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_finished_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='tmp_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='tmp_first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='tmp_last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, blank=True, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                max_length=30, blank=True, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                max_length=150, blank=True, null=True, verbose_name='last name'),
        ),
        migrations.RunPython(migrate_empty_to_null),
        migrations.RemoveField(
            model_name='user',
            name='tmp_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tmp_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tmp_last_name',
        ),
    ]
