# Generated by Django 3.0.11 on 2021-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('on_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'General',
            },
        ),
    ]
