# Generated by Django 3.0.11 on 2021-03-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='maintenance_due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
