# Generated by Django 3.0.11 on 2020-11-26 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.Brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='fees',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.Fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_sets',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.GiftSet'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.Brand'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.Category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftsetcategory',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='gift_set_categories', to='core.MenuItem'),
        ),
        migrations.AddField(
            model_name='giftset',
            name='gift_set_categories',
            field=models.ManyToManyField(blank=True, related_name='gift_sets', to='core.GiftSetCategory'),
        ),
        migrations.AddField(
            model_name='fee',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.Brand'),
        ),
        migrations.AddField(
            model_name='discount',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.Brand'),
        ),
        migrations.AddField(
            model_name='cookingitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooking_items', to='core.MenuItem'),
        ),
        migrations.AddField(
            model_name='cookingitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_items', to='core.Order'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='brands', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='brand',
            name='time_slots',
            field=models.ManyToManyField(blank=True, related_name='brands', to='core.TimeSlot'),
        ),
        migrations.AlterUniqueTogether(
            name='usedtimeslot',
            unique_together={('time_slot', 'order', 'brand', 'date')},
        ),
    ]
