# Generated by Django 3.0.11 on 2020-12-01 14:44

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201127_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
