# Generated by Django 3.0.11 on 2020-12-03 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_favoriteitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteitem',
            unique_together={('menu_item', 'user')},
        ),
    ]
