# Generated by Django 3.0.11 on 2020-12-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201203_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refunded_psp_reference',
            new_name='refund_psp_reference',
        ),
    ]
