# Generated by Django 3.0.11 on 2020-12-08 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201207_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='lead_time',
            field=models.PositiveIntegerField(default=90, help_text='As minutes'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='usedtimeslot',
            unique_together={('time_slot', 'order', 'date')},
        ),
        migrations.CreateModel(
            name='BrandTimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.Brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='usedtimeslot',
            name='brand',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='brand_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.BrandTimeSlot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.TimeRange'),
        ),
    ]
