# Generated by Django 3.0.11 on 2020-12-11 10:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201209_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='order_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('accepted', 'Take away')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fee',
            name='order_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('accepted', 'Take away')], max_length=25),
        ),
    ]
