# Generated by Django 3.0.11 on 2020-12-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201211_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='core.Location'),
        ),
    ]
