# Generated by Django 3.0.11 on 2020-12-13 17:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_brand_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='order_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('take_away', 'Take away')], max_length=26),
        ),
        migrations.AlterField(
            model_name='fee',
            name='order_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('take_away', 'Take away')], max_length=26),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('take_away', 'Take away')], default='dine_in', max_length=15),
        ),
    ]
