# Generated by Django 3.0.11 on 2020-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201214_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='brand',
            name='cooking_time',
            field=models.PositiveIntegerField(default=30, help_text='As minutes'),
        ),
        migrations.AddField(
            model_name='brand',
            name='delivery_time',
            field=models.PositiveIntegerField(default=60, help_text='As minutes'),
        ),
    ]
