# Generated by Django 3.0.11 on 2020-12-15 18:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201214_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTFee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.fee',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fees',
        ),
        migrations.AddField(
            model_name='fee',
            name='is_gst',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat Value')], default='flat', max_length=10)),
                ('order_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('take_away', 'Take away')], max_length=26)),
                ('is_gst', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat Value')], default='flat', max_length=10)),
                ('order_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('take_away', 'Take away')], max_length=26)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
