# Generated by Django 3.0.11 on 2020-12-17 09:52

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201217_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdyenResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', jsonfield.fields.JSONField(default=dict)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
