# Generated by Django 3.0.11 on 2020-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adyenresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedtimeslot',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='usedtimeslot',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
