# Generated by Django 3.0.11 on 2020-12-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201223_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
    ]
