# Generated by Django 3.0.11 on 2021-01-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210102_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedtimeslot',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='used_time_slot', to='core.Order'),
        ),
    ]
