# Generated by Django 3.0.11 on 2021-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210108_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingitem',
            name='status',
            field=models.CharField(choices=[('cooking', 'Cooking'), ('cooked', 'Cooked'), ('picked_up', 'Picked Up')], default='cooking', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checked_out', 'Checked out'), ('failed', 'Failed'), ('received', 'Received'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('cooked', 'Cooked'), ('ready_to_send', 'Ready to send')], default='checked_out', max_length=15),
        ),
    ]
