# Generated by Django 3.0.11 on 2021-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210111_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('service', 'Service')], default='kitchen', max_length=15),
        ),
    ]
