# Generated by Django 3.0.11 on 2021-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210114_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checked_out', 'Checked out'), ('failed', 'Failed'), ('received', 'Received'), ('rejected', 'Rejected'), ('pending_rejection', 'Pending Rejection'), ('accepted', 'Accepted'), ('cooking', 'Cooking'), ('cooked', 'Cooked'), ('ready_to_send', 'Ready to send'), ('on_the_way', 'On the way'), ('completed', 'Completed')], default='checked_out', max_length=30),
        ),
    ]
