# Generated by Django 3.0.11 on 2021-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210126_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
