# Generated by Django 3.0.11 on 2021-02-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_menuitem_no_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(blank=True,  default=''),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderfee',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='core.Order'),
        ),
        migrations.AddIndex(
            model_name='favoriteitem',
            index=models.Index(
                fields=['user', 'menu_item'], name='core_favori_user_id_197cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteitem',
            index=models.Index(
                fields=['user'], name='core_favori_user_id_83e8d0_idx'),
        ),
    ]
