# Generated by Django 3.0.11 on 2021-02-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210219_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
