# Generated by Django 3.0.11 on 2021-03-05 09:12

import core.models.brand
import core.models.menu_item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='menu_item_placeholder',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.brand.generate_media_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.brand.generate_media_path),
        ),
        migrations.AddField(
            model_name='brand',
            name='menu_item_placeholder',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.brand.generate_media_path),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.menu_item.generate_media_path),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='thumbnail',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.menu_item.generate_media_path),
        ),
    ]
