# Generated by Django 3.0.11 on 2021-03-10 06:28

import core.models.brand
from django.db import migrations, models
import utils.validators.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210305_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='image',
            new_name='media'
        ),
        migrations.AlterField(
            model_name='brand',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=core.models.brand.generate_media_path, validators=[
                                   utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*', 'video/*'])]),
        ),
        migrations.AddField(
            model_name='brand',
            name='media_type',
            field=models.CharField(blank=True, choices=[(
                'video', 'Video'), ('image', 'Image')], default='image', max_length=15),  # Default is image because all old fields are image
        ),
        migrations.AlterField(
            model_name='brand',
            name='media_type',
            field=models.CharField(blank=True, choices=[(
                'video', 'Video'), ('image', 'Image')], default='', max_length=15),
        ),
    ]
