# Generated by Django 3.0.11 on 2021-03-18 07:13

import core.models.location
from django.db import migrations, models
import utils.validators.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210310_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.location.generate_media_path, validators=[
                                    utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*'])]),
        ),
    ]
