# Generated by Django 3.0.11 on 2021-02-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('media', models.URLField()),
                ('number_of_like', models.PositiveIntegerField(default=0)),
                ('cooking_item', models.PositiveIntegerField()),
                ('serving', models.PositiveIntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='recipes', to='community.Chef')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChefTag',
            fields=[
                ('name', models.CharField(max_length=200,
                                          primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='ingredients', to='community.ChefRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='ChefRecipeDirection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='directions', to='community.ChefRecipe')),
            ],
        ),
        migrations.CreateModel(
            name='ChefPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('media', models.URLField()),
                ('number_of_like', models.PositiveIntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='posts', to='community.Chef')),
                ('tags', models.ManyToManyField(blank=True,
                                                related_name='posts', to='community.ChefTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChefMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('number_of_view', models.PositiveIntegerField(default=0)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='media', to='community.Chef')),
                ('tags', models.ManyToManyField(blank=True,
                                                related_name='media', to='community.ChefTag')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Chef Media'
            },
        ),
    ]
