# Generated by Django 3.0.11 on 2021-02-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_chefmedia_chefpost_chefrecipe_chefrecipedirection_chefrecipeingredient_cheftag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='youtube_video',
        ),
        migrations.CreateModel(
            name='ChefProfileMedia',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='profile_media', to='community.Chef')),
            ],
            options={
                'verbose_name_plural': 'Video/Media',
            },
        ),
        migrations.AlterModelOptions(
            name='chefmedia',
            options={'verbose_name_plural': 'Chef media'},
        ),
        migrations.RemoveField(
            model_name='chefpost',
            name='number_of_like',
        ),
        migrations.RemoveField(
            model_name='chefrecipe',
            name='number_of_like',
        ),
        migrations.AddField(
            model_name='chefpost',
            name='number_of_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefrecipe',
            name='number_of_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikedChefRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='likes', to='community.ChefRecipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='liked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LikedChefPost',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='likes', to='community.ChefPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='liked_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LikedChefMedia',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='likes', to='community.ChefMedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='liked_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('media', 'user')},
            },
        ),
    ]
