# Generated by Django 3.0.11 on 2021-03-05 09:12
import community.models.chef
import community.models.chef_media
import community.models.chef_post
import community.models.chef_recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210224_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chefmedia',
            name='url',
        ),
        migrations.RemoveField(
            model_name='chefpost',
            name='media',
        ),
        migrations.RemoveField(
            model_name='chefprofilemedia',
            name='url',
        ),
        migrations.RemoveField(
            model_name='chefrecipe',
            name='media',
        ),
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to=community.models.chef.generate_media_path),
        ),
        migrations.AddField(
            model_name='chefmedia',
            name='url',
            field=models.ImageField(
                default='', upload_to=community.models.chef_media.generate_media_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefpost',
            name='media',
            field=models.ImageField(
                default='', upload_to=community.models.chef_post.generate_media_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefprofilemedia',
            name='url',
            field=models.ImageField(
                blank=True, null=True, upload_to=community.models.chef.generate_media_path),
        ),
        migrations.AddField(
            model_name='chefrecipe',
            name='media',
            field=models.ImageField(
                default='', upload_to=community.models.chef_recipe.generate_media_path),
            preserve_default=False,
        ),
    ]
