# Generated by Django 3.0.11 on 2021-03-08 09:52

import community.models.chef
import community.models.chef_media
import community.models.chef_post
import community.models.chef_recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210305_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefprofilemedia',
            old_name='url',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='chefmedia',
            old_name='url',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='chefmedia',
            name='media',
            field=models.FileField(
                upload_to=community.models.chef_media.generate_media_path),
        ),
        migrations.AlterField(
            model_name='chefpost',
            name='media',
            field=models.FileField(
                upload_to=community.models.chef_post.generate_media_path),
        ),
        migrations.AlterField(
            model_name='chefprofilemedia',
            name='media',
            field=models.FileField(
                blank=True, null=True, upload_to=community.models.chef.generate_media_path),
        ),
        migrations.AlterField(
            model_name='chefrecipe',
            name='media',
            field=models.FileField(
                upload_to=community.models.chef_recipe.generate_media_path),
        ),
    ]
