# Generated by Django 3.0.11 on 2021-03-09 13:51

import community.models.chef
import community.models.chef_media
import community.models.chef_post
import community.models.chef_recipe
from django.db import migrations, models
import utils.validators.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20210308_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefprofilemedia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chefprofilemedia',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chefmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='chefpost',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='chefprofilemedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='chefrecipe',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='chefmedia',
            name='media',
            field=models.FileField(upload_to=community.models.chef_media.generate_media_path, validators=[utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*', 'video/*'])]),
        ),
        migrations.AlterField(
            model_name='chefpost',
            name='media',
            field=models.FileField(upload_to=community.models.chef_post.generate_media_path, validators=[utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*', 'video/*'])]),
        ),
        migrations.AlterField(
            model_name='chefprofilemedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=community.models.chef.generate_media_path, validators=[utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*', 'video/*'])]),
        ),
        migrations.AlterField(
            model_name='chefrecipe',
            name='media',
            field=models.FileField(upload_to=community.models.chef_recipe.generate_media_path, validators=[utils.validators.file_validator.FileTypeValidator(allowed_types=['image/*', 'video/*'])]),
        ),
    ]
