# Generated by Django 3.0.11 on 2021-02-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_menuitem_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMenuItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_menuitem_orders', to='core.Brand')),
                ('menu_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_menuitem_orders', to='core.MenuItem')),
            ],
            options={
                'unique_together': {('menu_item', 'brand', 'order'), ('menu_item', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='BrandCategoryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category_orders', to='core.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category_orders', to='core.Category')),
            ],
            options={
                'unique_together': {('category', 'brand', 'order'), ('category', 'brand')},
            },
        ),
    ]
