""" group_permission.py """
from user_management.constants.groups import (
    CUSTOMER, KITCHEN_STAFF, FRONT_DESK_STAFF, CONTENT_MANAGER)

# Declare group and permission per model
# 4 methods: add, view, change, delete
# if we don't want to set  permission, just don't put anything
GROUPS = {
    CUSTOMER: {
        "user": ["view", "change"],
        "brand": ["view"],
        "category": ["view"],
        "giftsetcategory": ["view"],
        "giftset": ["view"],
        "location": ["add", "delete", "change", "view"],
        "menuitem": ["view"],
        "favoriteitem": ["add", "delete", "view"],
        "discount": ["view"],
        "fee": ["view"],
        "order": ["add", "view"],
        "tag": ["view"],
        "timeslot": ["view"],
        "usedtimeslot": ["view"],
        "chef": ["view"],
        "chefpost": ["view"],
        "chefmedia": ["view"],
        "chefrecipe": ["view"],
        "cheffollower": ["add", "delete", "change", "view"],
    },

    # TODO: Permissions for staff will do later
    KITCHEN_STAFF: {
        "user": ["view", "change"],
        "brand": ["view"],
        "category": ["view"],
        "cookingitem": ["change", "view"],
        "giftsetcategory": ["view"],
        "giftset": ["view"],
        "location": ["add", "delete", "change", "view"],
        "menuitem": ["view"],
        "discount": ["view"],
        "fee": ["view"],
        "order": ["change", "view"],
        "ordercomment": ["add", "delete", "change", "view"],
        "tag": ["view"],
        "timeslot": ["view"],
        "usedtimeslot": ["view"],
        "chef": ["view"],
        "chefpost": ["view"],
        "chefmedia": ["view"],
        "chefrecipe": ["view"],
    },

    FRONT_DESK_STAFF: {
        "user": ["view", "change"],
        "brand": ["view"],
        "category": ["view"],
        "cookingitem": ["change", "view"],
        "giftsetcategory": ["view"],
        "giftset": ["view"],
        "location": ["add", "delete", "change", "view"],
        "menuitem": ["view"],
        "discount": ["view"],
        "fee": ["view"],
        "order": ["change", "view"],
        "ordercomment": ["add", "delete", "change", "view"],
        "tag": ["view"],
        "timeslot": ["view"],
        "usedtimeslot": ["view"],
        "chef": ["view"],
        "chefpost": ["view"],
        "chefmedia": ["view"],
        "chefrecipe": ["view"],
    },

    CONTENT_MANAGER: {
        "brand": ["view", "add", "change", "delete"],
        "category": ["view", "add", "change", "delete"],
        "cookingitem": ["change", "view"],
        "giftsetcategory": ["view", "add", "change", "delete"],
        "giftset": ["view", "add", "change", "delete"],
        "location": ["add", "delete", "change", "view"],
        "menuitem": ["view", "add", "change", "delete"],
        "discount": ["view", "add", "change", "delete"],
        "fee": ["view", "add", "change", "delete"],
        "gstfee": ["view", "add", "change", "delete"],
        "order": ["view"],
        "ordercomment": ["view"],
        "orderdiscount": ["view"],
        "orderfee": ["view"],
        "orderitem": ["view"],
        "tag": ["view", "add", "change", "delete"],
        "brandtimeslot": ["view", "add", "change", "delete"],
        "timeslot": ["view", "add", "change", "delete"],
        "usedtimeslot": ["view"],
        "chef": ["view", "add", "change", "delete"],
        "chefpost": ["view", "add", "change", "delete"],
        "chefmedia": ["view", "add", "change", "delete"],
        "chefrecipe": ["view", "add", "change", "delete"],
        "brandcategoryorder": ["view", "add", "change", "delete"],
        "brandmenuitemorder": ["view", "add", "change", "delete"],
        "brandorder": ["view", "add", "change", "delete"],
    },

}
