name: Deploy tabletop-v2-prod

on:
  push:
    branches: [master]

jobs:
  build:
    name: AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9.1]
    steps:
      - name: Check user permission
        id: check-admin-permission
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: The permission check failed
        if: "! steps.check-admin-permission.outputs.has-permission"
        run: echo "Sorry! Your permissions are insufficient."

      - name: Check out code
        if: steps.check-admin-permission.outputs.has-permission
        uses: actions/checkout@v2

      - name: Generate deployment package
        if: steps.check-admin-permission.outputs.has-permission
        run: |
          zip -r deployment.zip ./  -x \"*.git*\" -x \".env\" -x \"static/*\" -x \"*.zip\

      - name: Deploy to EB
        if: steps.check-admin-permission.outputs.has-permission
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tabletop-v2
          environment_name: tabletop-v2-prod
          version_label: ${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deployment.zip
          use_existing_version_if_available: true
